sudo: required
dist: trusty
services:
  - docker
addons:
  artifacts:
    debug: true
    s3_region: us-west-1
    target_paths: gridware_builds
    working_dir: $HOME
    paths:
      - build-$TRAVIS_BUILD_NUMBER
env:
  - cw_DIST=el7 cw_VERSION=1.4.0
  - cw_DIST=el6 cw_VERSION=1.4.0
matrix:
  allow_failures:
    - env: cw_DIST=el6 cw_VERSION=1.4.0
before_install:
  - .travis/build-container.sh
script:
  - .travis/run-tests.sh
