sudo: required
dist: trusty
services:
  - docker
addons:
  artificats:
    s3_region: "eu-west-1"
    target_paths: gridware_builds
    working_dir: $HOME
    paths:
    - build-$TRAVIS_BUILD_NUMBER
    debug: true
env:
  - cw_DIST=el7 cw_VERSION=1.4.0
  - cw_DIST=el7 cw_VERSION=1.4.1
  - cw_DIST=el6 cw_VERSION=1.4.0
  - cw_DIST=el6 cw_VERSION=1.4.1
before_install:
  - .travis/build-container.sh
script:
  - .travis/run-tests.sh
